version: 2.1
jobs: # 有哪些工作
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache: # 回復依賴
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run: # 安裝依賴
          name: Install Dependency
          command: yarn
      - save_cache: # 儲存依賴
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run: # 靜態檢查
          name: Lint Code
          command: yarn lint

  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache: # 回復依賴
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run: # 編譯靜態檔案
          name: Generate Static File
          command: yarn build
      - persist_to_workspace: # 儲存編譯好的檔案
          root: dist
          paths: '*'

  deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - attach_workspace: # 回復編譯好的檔案
          at: dist
      - run:
          name: Custom Domain
          command: echo 'qr-code.mailvd.com' > CNAME
      - run:
          name: Install and configure dependencies
          command: |
            sudo npm install -g --silent gh-pages
            git config user.email $GH_EMAIL
            git config user.name $GH_NAME
      - add_ssh_keys:
          fingerprints:
            - "d4:96:0b:d2:6e:2b:c7:54:bd:82:a6:f2:29:a3:6d:5c"
      - run:
          name: Deploy dist to gh-pages branch
          command: sudo gh-pages --dotfiles --message "[skip ci] Updates" --dist dist

workflows:
  version: 2
  deploy-workflow: # 部署流程
    jobs: # 哪些 job 是要執行的
      - test

      - build: # 編譯任務
          requires:
            - test # 測試任務
          filters:
            branches:
              only: master # 適用 master

      - deploy: # 部署
          requires:
            - test # 測試任務
            - build # 編譯任務
          filters:
            branches:
              only: master # 適用 master

  daily-workflow: # 每日任務
    triggers:
      - schedule:
          cron: '00 23 * * *' # UTC +0 19:30 PM = 隔天 UTC +8 3:30 AM
          filters:
            branches:
              only: /.*/

    jobs:
      - test
